# Generated by Django 5.0.7 on 2025-02-11 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SchedulerApp", "0010_remove_course_max_numb_students_course_max_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="room",
        ),
    ]
